### ISSUE TITLE
ログイン認証

### ISSUE THREAD

**Issue by topaoad** [qin-team-recipe/02-frontend#20]
## feature/authenticationブランチで実装中ですが、完了するまでメインブランチへのマージは保留中

【進捗】
- ひとまずuser情報で認証管理を行い、後日トークンとクッキーに置き換える予定をしていた
- しかし、Contextを使い、ルートレイアウトで全コンポーネント共通で状態管理をさせるために作成した
AuthedCheckProviderコンポーネントでuser情報が保持できず、作業保留中
- Recoilでも試したが結果は同じ
- user情報は各ページからは取得可能
- 週末しまぶーさんにアドバイスを求める予定
- トークンを用いてクッキーをセットし、クッキー情報を元に判別する方法しかないのか思案中

**Comment by DaisukeTujita** [comment]
見当違いなこと言っていたらすみません。
コンテキストへ登録するデータの型が一致していないかもと思いました。
userInfoのレスポンスの形が添付の画像のようなものなので、以下26行目のsetUset(data)をsetUser(data.data)にするとユーザ情報を登録することができました。

https://github.com/qin-team-recipe/02-frontend/blob/83d311d3e3ddea7c2fad5f1c970f800f57522129/src/app/auth/callback/google/page.tsx#L24-L29

![image](https://github.com/qin-team-recipe/02-frontend/assets/5800064/6faad668-8a1b-4169-8e0a-bbc78ee90da0)

**Comment by DaisukeTujita** [comment]
余計かもしれませんが、個人的に認証処理の理解を深めるために、現在作成いただいている処理の流れを簡単に図化してみました。

![image](https://github.com/qin-team-recipe/02-frontend/assets/5800064/6b6377b2-e654-4269-9ffd-9142ef67a261)

**Comment by topaoad** [comment]
おかげさまで解決しましたし、図によってわかりやすく可視化できました！
感謝感謝です。
ありがとうございましたー！！

**Comment by topaoad** [comment]
実装が一旦完了したのでクローズします
